# Generated by Django 5.1.4 on 2025-01-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_about_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
